Added Transform Functionality to DataTable.svelte & updated README.md
HealthTree/svelte-data-table pull request #4
Opened 2021-05-13 19:52 UTC by anti-h3r0

## Description
title says it all

Closes #299 .

2021-05-13 23:47 UTC, diegofhe approved these changes
LGTM, Just see my comments

2021-05-13 23:47 UTC, diegofhe commented on src/components/DataTable.svelte
> +				val = get(tempRow, field, null);
null can be omitted, is the default

2021-05-13 23:47 UTC, diegofhe commented on src/components/DataTable.svelte
> +				val = get(tempRow, target, null);
same here

2021-05-13 23:47 UTC, diegofhe commented on src/components/DataTable.svelte
> +				throw new Error('transform is not configured correctly, please read the documentation')
nice

2021-05-13 23:50 UTC, diegofhe requested changes

2021-05-13 23:50 UTC, diegofhe commented on src/components/DataTable.svelte
> +			if (!val) console.error(`the property 'row.${transform.field || field}' is undefined.\n\t\t assigning value to null`)
Watch out. This will console on falsy values like 0 and false. I would check for undefined or null for this kind of logic. But for this specific case, I would delete this console error, maybe the user wants the property to be undefined or null

2021-05-14 10:11 UTC, anti-h3r0 commented on src/components/DataTable.svelte
> +			if (!val) console.error(`the property 'row.${transform.field || field}' is undefined.\n\t\t assigning value to null`)
oh okay

2021-05-14 16:51 UTC, diegofhe approved these changes
LGTM

2021-05-16 14:10 UTC, merged